version: "2.4"

services:
  django:
    build:
      context: .
      dockerfile: ./configs/django/Dockerfile
    volumes:
      - ./volumes/static:/static
      - ./volumes/media:/media
    restart: on-failure
    env_file:
      - ./configs/django/environment.env
      - ./configs/postgres/environment.env
      - ./configs/rabbitmq/environment.env

  celery:
    build:
      context: .
      dockerfile: ./configs/celery/Dockerfile
    volumes:
      - ./volumes/celery:/celery
      - ./volumes/media:/media
    restart: on-failure
    env_file:
      - ./configs/django/environment.env
      - ./configs/postgres/environment.env
      - ./configs/rabbitmq/environment.env
    environment:
      - CELERY_CONTAINER_TYPE=worker

  flower:
    build:
      context: .
      dockerfile: configs/celery/Dockerfile
    volumes:
      - ./volumes/celery:/celery
      - ./volumes/media:/media
    restart: on-failure
    env_file:
      - ./configs/django/environment.env
      - ./configs/postgres/environment.env
      - ./configs/rabbitmq/environment.env
      - ./configs/celery/flower.env
    environment:
      - CELERY_CONTAINER_TYPE=flower

  nginx:
    image: nginx:1.15.9-alpine
    volumes:
      - ./configs/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./configs/nginx/proxy_params:/etc/nginx/proxy_params
      - ./configs/nginx/robots.txt:/var/www/ctforces/robots.txt:ro
      - ./volumes/static:/static:ro
      - ./volumes/media:/media:ro
      - ./ctforces_frontend/dist:/front:ro
      - ./volumes/certbot/conf:/etc/letsencrypt
      - ./volumes/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure

  certbot:
    image: certbot/certbot
    volumes:
      - ./volumes/certbot/conf:/etc/letsencrypt
      - ./volumes/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: on-failure

  postgres:
    image: postgres:12.1
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
    restart: on-failure
    env_file:
      - ./configs/postgres/environment.env

  redis:
    image: redis:5.0.9-alpine
    restart: on-failure
    sysctls:
      net.core.somaxconn: 1024

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.8.3-management-alpine
    restart: on-failure
    ports:
      - "15672:15672"
    env_file:
      - configs/rabbitmq/environment.env
