version: "2.2"

services:
  ctforces_django:
    build:
      context: .
      dockerfile: ./configs/django.Dockerfile
    volumes:
      - ./volumes/static:/static
      - ./volumes/media:/media
      - ./volumes/socks:/socks
      - ./volumes/server_logs:/logs
    depends_on:
      - ctforces_postgres
      - ctforces_redis
    restart: on-failure
    container_name: ctforces_django
    env_file:
      - ./configs/environment.dev.env

  ctforces_celery:
    build:
      context: .
      dockerfile: ./configs/celery.Dockerfile
    volumes:
      - ./volumes/celery:/celery
      - ./volumes/media:/media
    depends_on:
      - ctforces_redis
    restart: on-failure
    container_name: ctforces_celery
    env_file:
      - configs/environment.dev.env

  ctforces_flower:
    build:
      context: .
      dockerfile: ./configs/flower.Dockerfile
    volumes:
      - ./volumes/celery:/celery
      - ./volumes/media:/media
      - ./volumes/socks:/socks
    depends_on:
      - ctforces_redis
      - ctforces_celery
    restart: on-failure
    container_name: ctforces_flower
    env_file:
      - configs/environment.dev.env

  ctforces_nginx:
    image: nginx
    volumes:
      - ./configs/nginx:/etc/nginx/conf.d
      - ./configs/nginx.proxy_params:/etc/nginx/proxy_params
      - ./volumes/static:/static:ro
      - ./volumes/socks:/socks
      - ./volumes/media:/media:ro
      - ./volumes/react_build:/react_build:ro
    depends_on:
      - ctforces_django
      - ctforces_react
    ports:
      - "8000:80"
    restart: on-failure
    container_name: ctforces_nginx

  ctforces_postgres:
    build:
      context: .
      dockerfile: configs/postgres.Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/db/postgresql/:/var/lib/postgresql/
    restart: on-failure
    container_name: ctforces_postgres
    env_file:
      - ./configs/environment.dev.env

  ctforces_redis:
    image: redis
    container_name: ctforces_redis

  ctforces_react:
    build:
      context: .
      dockerfile: configs/react.dev.Dockerfile
    volumes:
      - ./volumes/react_build:/react_build
    restart: on-failure
    container_name: ctforces_react
    env_file:
      - configs/environment.dev.env
